Controllers/AvaliacaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2entregaProjetoFinal.Models;

namespace _2entregaProjetoFinal.Controllers
{
    public class AvaliacaosController : Controller
    {
        private readonly Context _context;

        public AvaliacaosController(Context context)
        {
            _context = context;
        }

        // GET: Avaliacaos
        public async Task<IActionResult> Index()
        {
            var context = _context.avaliacoes.Include(a => a.CadastrarEstabelecimento).Include(a => a.CadastrarUsuario);
            return View(await context.ToListAsync());
        }

        // GET: Avaliacaos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avaliacao = await _context.avaliacoes
                .Include(a => a.CadastrarEstabelecimento)
                .Include(a => a.CadastrarUsuario)
                .FirstOrDefaultAsync(m => m.IdAvaliacao == id);
            if (avaliacao == null)
            {
                return NotFound();
            }

            return View(avaliacao);
        }

        // GET: Avaliacaos/Create
        public IActionResult Create()
        {
            ViewData["IdEstabelecimento"] = new SelectList(_context.estabelecimentos, "IdEstabelecimento", "IdEstabelecimento");
            ViewData["IdUsuario"] = new SelectList(_context.usuarios, "IdUsuario", "IdUsuario");
            return View();
        }

        // POST: Avaliacaos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAvaliacao,IdUsuario,IdEstabelecimento,NotaEstabelecimento,Comentario")] Avaliacao avaliacao)
        {
           
            _context.Add(avaliacao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            ViewData["IdEstabelecimento"] = new SelectList(_context.estabelecimentos, "IdEstabelecimento", "IdEstabelecimento", avaliacao.IdEstabelecimento);
            ViewData["IdUsuario"] = new SelectList(_context.usuarios, "IdUsuario", "IdUsuario", avaliacao.IdUsuario);
    
        }

        // GET: Avaliacaos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avaliacao = await _context.avaliacoes.FindAsync(id);
            if (avaliacao == null)
            {
                return NotFound();
            }
            ViewData["IdEstabelecimento"] = new SelectList(_context.estabelecimentos, "IdEstabelecimento", "IdEstabelecimento", avaliacao.IdEstabelecimento);
            ViewData["IdUsuario"] = new SelectList(_context.usuarios, "IdUsuario", "IdUsuario", avaliacao.IdUsuario);
            return View(avaliacao);
        }

        // POST: Avaliacaos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAvaliacao,IdUsuario,IdEstabelecimento,NotaEstabelecimento,Comentario")] Avaliacao avaliacao)
        {
            if (id != avaliacao.IdAvaliacao)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(avaliacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvaliacaoExists(avaliacao.IdAvaliacao))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstabelecimento"] = new SelectList(_context.estabelecimentos, "IdEstabelecimento", "IdEstabelecimento", avaliacao.IdEstabelecimento);
            ViewData["IdUsuario"] = new SelectList(_context.usuarios, "IdUsuario", "IdUsuario", avaliacao.IdUsuario);
            return View(avaliacao);
        }

        // GET: Avaliacaos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avaliacao = await _context.avaliacoes
                .Include(a => a.CadastrarEstabelecimento)
                .Include(a => a.CadastrarUsuario)
                .FirstOrDefaultAsync(m => m.IdAvaliacao == id);
            if (avaliacao == null)
            {
                return NotFound();
            }

            return View(avaliacao);
        }

        // POST: Avaliacaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var avaliacao = await _context.avaliacoes.FindAsync(id);
            _context.avaliacoes.Remove(avaliacao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvaliacaoExists(int id)
        {
            return _context.avaliacoes.Any(e => e.IdAvaliacao == id);
        }
    }
}

Controllers/CadastrarEstabelecimentoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2entregaProjetoFinal.Models;

namespace _2entregaProjetoFinal.Controllers
{
    public class CadastrarEstabelecimentoesController : Controller
    {
        private readonly Context _context;

        public CadastrarEstabelecimentoesController(Context context)
        {
            _context = context;
        }

        // GET: CadastrarEstabelecimentoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.estabelecimentos.ToListAsync());
        }

        // GET: CadastrarEstabelecimentoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarEstabelecimento = await _context.estabelecimentos
                .FirstOrDefaultAsync(m => m.IdEstabelecimento == id);
            if (cadastrarEstabelecimento == null)
            {
                return NotFound();
            }

            return View(cadastrarEstabelecimento);
        }

        // GET: CadastrarEstabelecimentoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastrarEstabelecimentoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEstabelecimento,NomeEstabelecimento,NotaEstabelecimento,HorarioFuncionamento,ComentariosEstabelecimento,AcessibilidadesEstabelecimentos")] CadastrarEstabelecimento cadastrarEstabelecimento)
        {
            _context.Add(cadastrarEstabelecimento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: CadastrarEstabelecimentoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarEstabelecimento = await _context.estabelecimentos.FindAsync(id);
            if (cadastrarEstabelecimento == null)
            {
                return NotFound();
            }
            return View(cadastrarEstabelecimento);
        }

        // POST: CadastrarEstabelecimentoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEstabelecimento,NomeEstabelecimento,NotaEstabelecimento,HorarioFuncionamento,ComentariosEstabelecimento,AcessibilidadesEstabelecimentos")] CadastrarEstabelecimento cadastrarEstabelecimento)
        {
            if (id != cadastrarEstabelecimento.IdEstabelecimento)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cadastrarEstabelecimento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastrarEstabelecimentoExists(cadastrarEstabelecimento.IdEstabelecimento))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cadastrarEstabelecimento);
        }

        // GET: CadastrarEstabelecimentoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarEstabelecimento = await _context.estabelecimentos
                .FirstOrDefaultAsync(m => m.IdEstabelecimento == id);
            if (cadastrarEstabelecimento == null)
            {
                return NotFound();
            }

            return View(cadastrarEstabelecimento);
        }

        // POST: CadastrarEstabelecimentoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cadastrarEstabelecimento = await _context.estabelecimentos.FindAsync(id);
            _context.estabelecimentos.Remove(cadastrarEstabelecimento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CadastrarEstabelecimentoExists(int id)
        {
            return _context.estabelecimentos.Any(e => e.IdEstabelecimento == id);
        }
    }
}

Controllers/CadastrarUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2entregaProjetoFinal.Models;

namespace _2entregaProjetoFinal.Controllers
{
    public class CadastrarUsuariosController : Controller
    {
        private readonly Context _context;

        public CadastrarUsuariosController(Context context)
        {
            _context = context;
        }

        // GET: CadastrarUsuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.usuarios.ToListAsync());
        }

        // GET: CadastrarUsuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarUsuario = await _context.usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (cadastrarUsuario == null)
            {
                return NotFound();
            }

            return View(cadastrarUsuario);
        }

        // GET: CadastrarUsuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastrarUsuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuario,NomeUsuario,NessecidadeEspecial,UserName,Data_Nascimento,Senha")] CadastrarUsuario cadastrarUsuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cadastrarUsuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cadastrarUsuario);
        }

        // GET: CadastrarUsuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarUsuario = await _context.usuarios.FindAsync(id);
            if (cadastrarUsuario == null)
            {
                return NotFound();
            }
            return View(cadastrarUsuario);
        }

        // POST: CadastrarUsuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,NomeUsuario,NessecidadeEspecial,UserName,Data_Nascimento,Senha")] CadastrarUsuario cadastrarUsuario)
        {
            if (id != cadastrarUsuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cadastrarUsuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastrarUsuarioExists(cadastrarUsuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cadastrarUsuario);
        }

        // GET: CadastrarUsuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastrarUsuario = await _context.usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (cadastrarUsuario == null)
            {
                return NotFound();
            }

            return View(cadastrarUsuario);
        }

        // POST: CadastrarUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cadastrarUsuario = await _context.usuarios.FindAsync(id);
            _context.usuarios.Remove(cadastrarUsuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CadastrarUsuarioExists(int id)
        {
            return _context.usuarios.Any(e => e.IdUsuario == id);
        }
    }
}

Controllers/HomeController.cs
using _2entregaProjetoFinal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace _2entregaProjetoFinal.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Cadastro()
    {
      return View();
    }
    public IActionResult Contato()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    public IActionResult Locais()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Views/Home/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

<div class="conteiner-fluid">
    <div class="row p-3">
        <div class="col-lg-6 col-12">
            <h2 class="shadow-sm p-3 mb-5 bg-white rounded d-flex justify-content-center font-weight-bold">Faça seu
                login:</h2>

            <form class="needs-validation" novalidate>
                <div class="form-group">
                    <label for="EmailLogin">Endereço de email: </label>
                    <input type="email" class="form-control" id="EmailLogin" name="EmailLogin"
                        placeholder="Digite seu email para login" required>
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <div class="form-group">
                    <label for="SenhaLogin">Senha: </label>
                    <input type="password" class="form-control" id="SenhaLogin" name="SenhaLogin"
                        placeholder="Digite a senha." required>
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="ManterConectado" id="ManterConectado">
                    <label class="form-check-label mb-1" for="ManterConectado">Lembrar da senha.</label>
                </div>
                <button type="submit" class="btn btn-outline-primary">Entrar</button>
            </form>

            <div class="container-fluid">
                <h5 class="shadow-sm p-3 mb-2 bg-white rounded d-flex justify-content-center font-weight-bold">Login pelas redes sociais:</h5>
                <ul class="socialLinks d-flex justify-content-center">
                     <li class="google">
                        <a target="_blank" href="#">
                             <div id="buttonDiv"></div>
                        </a>
                    </li>
                    <li class="twitter">
                        <a href="#" target="_blank">
                            <i class="bi bi-twitter"></i>
                        </a>
                    </li>
                    <li class="facebook">
                        <a target="_blank" href="#">
                            <i class="bi bi-facebook"></i>
                        </a>
                    </li>
                    <li class="instagram">
                        <a target="_blank" href="#">
                            <i class="bi bi-instagram"></i>
                        </a>
                    </li>
                </ul>
            </div>

        </div>
        <ul type="none">
            <li>Área dos Usuários:</li>
            <li><a asp-action="Create" asp-controller="CadastrarUsuarios"><button>Cadastra-se Aqui</button></a></li>
            <li><a asp-action="Create" asp-controller="Avaliacaos"><button>Avalie Aqui</button></a></li>
            <li><a asp-action="Index" asp-controller="Avaliacaos"><button>Consultar Avaliações</button></a></li>
        </ul>
        <br>
        <ul type="none">
            <li>Área dos Administradores:</li>
            <li><a asp-action="Create" asp-controller="CadastrarEstabelecimentoes"><button>Cadastrar Estabelecimento</button></a></li>
            <li><a asp-action="Index" asp-controller="CadastrarEstabelecimentoes"><button>Consultar Estabelecimentos</button></a></li>
            <li><a asp-action="Index" asp-controller="CadastrarUsuarios"><button>Consultar Usuários</button></a></li> 
        </ul>

        <div class="col-lg-6 col-12">
            <h2 class="shadow-sm p-3 mb-5 bg-white rounded d-flex justify-content-center font-weight-bold">Faça seu
                cadastro:</h2>

            <form class="needs-validation" novalidate>
                <div class="form-group">
                    <label for="NomeCadastro">Nome:</label>
                    <input type="text" class="form-control" id="NomeCadastro" name="NomeCadastro"
                        placeholder="Digite seu nome." required>
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <div class="form-group">
                    <label for="NomeSocialCadastro">Nome social:</label>
                    <input type="text" class="form-control" id="NomeSocialCadastro" name="NomeSocialCadastro"
                        placeholder="Digite seu nome social.">
                </div>
                <div class="form-group">
                    <label for="EmailCadastro">Email:</label>
                    <input type="email" class="form-control" id="EmailCadastro" placeholder="Digite seu email"
                        name="EmailCadastro" required>                    
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <div class="form-group">
                    <label for="DataNascimentoCadastro">Data de nascimento:</label>
                    <input type="date" id="DataNascimentoCadastro" name="DataNascimentoCadastro" required>
                </div>
                <div class="form-group">
                    <label for="SenhaCadastro">Senha:</label>
                    <input type="password" class="form-control" id="SenhaCadastro" placeholder="Digite a senha."
                        name="SenhaCadastro" required>                    
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <div class="form-group">
                    <label for="SenhaCadastroConfirmacao">Confirme a senha:</label>
                    <input type="password" class="form-control" id="SenhaCadastroConfirmacao"
                        placeholder="Digite novamente a senha." name="SenhaCadastroConfirmacao" required>                    
                    <div class="invalid-feedback">Digite os dados corretamente!</div>
                </div>
                <button class="btn btn-outline-primary" type="submit">Cadastrar</button>
            </form>
        </div>
    </div>
</div>

Views/Home/Contato.cshtml
@{
    ViewData["Title"] = "Contato";
}

<div class="container-fluid">
    <h1>Entre em contato conosco</h1>
</div>
<main>
    <div class="container-fluid">
        <div class="row p-3">
            <div class="col-sm">
                <form target="_blank" action="https://formsubmit.co/appacecidade@gmail.com" method="POST"
                    enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Endereço de email</label>
                        <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
                            placeholder="nome@exemplo.com" required>
                        <div class="invalid-feedback">Digite seu email corretamente!
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Assunto">Assunto</label>
                        <input type="text" name="assunto" class="form-control" id="Assunto"
                            placeholder="Informe o assunto do contato" required>
                        <div class="invalid-feedback">Digite o assunto do seu contato!</div>
                    </div>
                    <div class="form-group">
                        <label for="SelectFeedback">Selecione o FeedBack</label>
                        <select class="form-control" name="select" id="SelectFeedback">
                            <option>Reportar um erro</option>
                            <option>Sugestões</option>
                            <option>Inlusão de estabelecimento</option>
                            <option>Reclamações</option>
                        </select>
                        <div class="invalid-feedback">Selecione uma opção!</div>
                    </div>

                    <div class="form-group">
                        <label for="DescricaoForm">Descrição</label>
                        <textarea class="form-control" name="DescricaoForm" rows="3"></textarea>
                        <div class="invalid-feedback">Digite os dados corretamente!</div>
                    </div>
                    <div class="form-group">
                        <label for="Anexo1">Selecione um anexo</label>
                        <input type="file" name="anexo" class="form-control-file" id="Anexo1">
                        <input type="hidden" name="_autoresponse"
                            value="Recebemos seu e-mail e logo retornaremos ! Att equipe AceCidade.">
                    </div>
                    <div>
                        <button class="btn btn-outline-primary" type="submit">Enviar</button>
                    </div>
                </form>
            </div>
            <div class="conteiner-fluid">
                <div class="row p-3">
                    <div class="col-sm d-flex pl-5 mt-n5 justify-content-center">
                        <img class="mt-n5" src="~/IMG/Acecidade.png" alt="logo">
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>